stages:
  - build

build-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY 
  script:
    - docker build --pull -t react-aws-ecs .
    - docker push react-aws-ecs
  only:
    - master
include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml
