version: '3'
services:
  redis-server:
    image: redis
  react-job-app:
    build: .
    ports:
      - "3081:3081"
    depends_on:
      - worker-jobs
      - redis-server
      - mdb
    environment:
      - MONGODB_URI=mongodb://mdb:27017/jobdb
      - REDIS_URI=redis-server
      - REDIS_PORT=6379
      - PORT=3081
      - NODE_ENV=production
    restart: always
  worker-jobs:
    build:
      context: .
      dockerfile: DockerfileWorker
    restart: always
    environment:
      - REDIS_URI=redis-server
      - REDIS_PORT=6379
    depends_on:
      - redis-server
  mdb:
    image: mongo
    restart: always
    ports:
      - 27017:27017



